package com.flowos.model;

public enum OrganizationIndustry {
    INFORMATION_TECHNOLOGY,
    PROFESSIONAL_SERVICES,
    SALES_AND_CRM,
    OPERATIONS,
    HUMAN_RESOURCES,
    FINANCE_AND_ACCOUNTING,
    EDUCATION,
    HEALTHCARE,
    MANUFACTURING,
    CONSTRUCTION,
    REAL_ESTATE,
    RETAIL,
    NON_PROFIT,
    LAW_FIRM,
    MARKETING_AGENCY,
    CONSULTING,
    GENERAL_BUSINESS
}
