package com.flowos.model;

public enum ProjectWorkType {
    GENERAL,
    CLIENT_PROJECT,
    INTERNAL_PROJECT,
    OPERATIONS_WORK,
    SALES_PIPELINE,
    HR_PROCESS,
    FINANCE_PROCESS,
    PROCUREMENT,
    CUSTOMER_SUPPORT,
    PRODUCT_DELIVERY,
    IMPLEMENTATION,
    EVENT,
    TRAINING,
    COMPLIANCE,
    MAINTENANCE,
    LEGAL_MATTER,
    MARKETING_CAMPAIGN,
    RETAINER,
    INTERNAL_OPERATIONS
}
